allowBuilds:
  esbuild: false
  node-libcurl: true
overrides:
  brace-expansion@<1.1.13: ^1.1.13
  brace-expansion@>=2.0.0 <2.0.3: ^2.0.3
  diff@>=4.0.0 <4.0.4: ^4.0.4
  flatted@<3.4.2: ^3.4.2
  glob@>=10.2.0 <10.5.0: ^10.5.0
  ip-address@<=10.1.0: ^10.1.1
  minimatch@<3.1.4: ^3.1.4
  minimatch@>=9.0.0 <9.0.7: ^9.0.7
  path-to-regexp@>=8.0.0 <8.4.0: ^8.4.0
  picomatch@>=4.0.0 <4.0.4: ^4.0.4
  postcss@<8.5.10: ^8.5.10
  qs@<6.14.1: ^6.14.1
  rollup@>=4.0.0 <4.59.0: ^4.59.0
  vite@>=6.0.0 <6.4.2: '^6.4.2'
